### ISSUE TITLE
Preassembled devices

### ISSUE THREAD

**Issue by maxkfranz** [jaytavares/cinesense#2]
Do you sell preassembled devices?  It's great that you've open-sourced the project, but I'd rather buy than DIY.

In any case, thanks for your project!  I've wanted to sort out this issue on my speakers for a while now.

My email address is maxkfranz@gmail.com

**Comment by jarevalo31** [comment]
Hi Jay. 

I'm also interested in a preassembled device. Can we connect to see if I can get one? Thanks! My email is jorge.arevalo@mac.com

**Comment by superwdy** [comment]
+1. @jaytavares DIY with soldering tools might not be a choice for lots of regular Bose consumers. It's be really helpful if you could sell it. I'm not sure about the market size but if you are interested in finding a manufacturer to bulk produce I could help with connecting you with some Chinese manufacturer.

**Comment by jaytavares** [comment]
Hey there. I've made some for people who are in your same position. I don't think there's enough demand to justify large scale manufacture. So, I've just been assembling small runs myself.

**Comment by maxkfranz** [comment]
@jaytavares, it might be useful to add contact information to the readme for people who’d like a preassembled device. Also, some people who self assemble may be interested in donating through GitHub sponsors. 

My main motivation was to support the author of the project, though I’d also rather not have a soldering project. It’s great to see open source projects like this one. Thanks, Jay.

**Comment by jaytavares** [comment]
> @jaytavares, it might be useful to add contact information to the readme for people who’d like a preassembled device. Also, some people who self assemble may be interested in donating through GitHub sponsors.
> 
> My main motivation was to support the author of the project, though I’d also rather not have a soldering project. It’s great to see open source projects like this one. Thanks, Jay.

Good idea @maxkfranz, I’ll add a note with some contact information to the readme.

**Comment by jaytavares** [comment]
@maxkfranz Oh and I also really appreciate your support!

**Comment by jipiboily** [comment]
Hello @jaytavares!

Would love to know if you are willing to build and sell one more?

if so, how can I reach you for the details? You can also email me at j@jipi.ca

Thanks!

**Comment by jaytavares** [comment]
> Hello @jaytavares!
> 
> Would love to know if you are willing to build and sell one more?
> 
> if so, how can I reach you for the details? You can also email me at [j@jipi.ca](mailto:j@jipi.ca)
> 
> Thanks!

I just added a direct purchase link to the [readme](https://github.com/jaytavares/cinesense). Hopefully this helps!
