### ISSUE TITLE
How can I get one?

### ISSUE THREAD

**Issue by treveles** [jaytavares/cinesense#3]
There is no way to private message using this platform, but I am desperate to have a cinesense built for me. Thank you in advance!

tiffanyreveles@gmail.com

**Comment by jaytavares** [comment]
Hi Tiffany! Just saw this. Sorry it was difficult to contact me. I'm glad you eventually were able to. I just added a direct purchase link to the readme and also added my email address to my GitHub profile. Hopefully that makes it a bit easier for others to contact me in the future!
